name: swarden
description: "Password manager app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  firebase_core: ^2.30.1
  shared_preferences: ^2.2.3
  go_router: ^14.0.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  url_launcher: ^6.2.6
  local_auth: ^2.3.0
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  rmove_alpha_ios: true
  image_path: "assets/img/icon.png"
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/img/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
