name: swarden
description: "Password manager app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  firebase_core: ^2.30.1
  shared_preferences: ^2.2.3
  go_router: ^14.0.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  url_launcher: ^6.2.6
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/
